# Generated by Django 6.0.4 on 2026-05-03 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_mfadevice_userprofile_usersession_invitation_and_more'),
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataResidencyRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country_codes', models.JSONField(blank=True, default=list)),
                ('storage_backend', models.CharField(blank=True, max_length=120)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationDataResidencyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enforcement_mode', models.CharField(choices=[('log_only', 'Log Only'), ('block', 'Block')], default='log_only', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_regions', models.ManyToManyField(blank=True, related_name='allowed_policies', to='compliance.dataresidencyregion')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_residency_policy', to='accounts.organization')),
                ('primary_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_policies', to='compliance.dataresidencyregion')),
            ],
        ),
    ]
