# Generated by Django 6.0.4 on 2026-05-03 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_storedfile_document_source_file_documentpage'),
        ('envelopes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_key', models.SlugField()),
                ('label', models.CharField(max_length=255)),
                ('routing_order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['routing_order'],
            },
        ),
        migrations.AddField(
            model_name='formfield',
            name='document_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='documents.documentpage'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='field_key',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='formfield',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='envelopes.templateparty'),
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('field_schema', models.JSONField(blank=True, default=dict)),
                ('workflow_schema', models.JSONField(blank=True, default=dict)),
                ('changelog', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_versions', to='documents.document')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='envelopes.template')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('template', 'version_number')},
            },
        ),
        migrations.AddField(
            model_name='templateparty',
            name='template_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='envelopes.templateversion'),
        ),
        migrations.AddField(
            model_name='envelope',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envelopes', to='envelopes.templateversion'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='template_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='envelopes.templateversion'),
        ),
        migrations.AlterUniqueTogether(
            name='templateparty',
            unique_together={('template_version', 'role_key')},
        ),
    ]
