# Generated by Django 6.0.4 on 2026-05-04 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0002_templateparty_formfield_document_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='delegated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipient',
            name='delegated_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegates', to='envelopes.recipient'),
        ),
        migrations.AddField(
            model_name='recipient',
            name='delegation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('declined', 'Declined'), ('delegated', 'Delegated')], default='pending', max_length=32),
        ),
    ]
