# Generated by Django 6.0.4 on 2026-05-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_recipient_delegated_at_recipient_delegated_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select'), ('checkbox', 'Checkbox'), ('signature', 'Signature'), ('initials', 'Initials'), ('attachment', 'Attachment')], max_length=32),
        ),
    ]
