# Generated by Django 6.0.4 on 2026-05-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCIMConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.URLField(blank=True)),
                ('token_prefix', models.CharField(blank=True, max_length=24)),
                ('token_hash', models.CharField(blank=True, max_length=128)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scim_connection', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SSOConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('provider_type', models.CharField(choices=[('saml', 'SAML'), ('oidc', 'OIDC'), ('ldap', 'LDAP')], max_length=32)),
                ('is_enabled', models.BooleanField(default=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('metadata_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_connections', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SCIMExternalIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='scim', max_length=80)),
                ('external_id', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_external_identities', to='accounts.organization')),
            ],
            options={
                'unique_together': {('organization', 'provider', 'external_id')},
            },
        ),
    ]
