# Generated by Codex on 2026-05-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountrecoveryrequest_passkeychallenge_recoverycode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mfadevice',
            name='credential_id',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='public_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mfadevice',
            name='sign_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
