# Generated by Django 6.0.4 on 2026-05-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_organization_parent_organizationdomain'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='logo',
            field=models.FileField(blank=True, upload_to='organization-logos/'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='token_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
