# Generated by Codex on 2026-05-12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_logo_alter_invitation_token_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.role'),
        ),
    ]
