# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_membership_invitation_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='auth_version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
