# Generated by Codex on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_auth_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='failed_login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_failed_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
