# Generated by Django 6.0.4 on 2026-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_impersonationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='impersonationrequest',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impersonationrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='impersonationrequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('active', 'Active'), ('ended', 'Ended'), ('denied', 'Denied'), ('expired', 'Expired')], default='requested', max_length=32),
        ),
    ]
