# Generated by Django 6.0.4 on 2026-05-04 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_accountrecoveryrequest_passkeychallenge_recoverycode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.PositiveBigIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('weight', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_index_entries', to='accounts.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'object_type'], name='search_sear_organiz_030190_idx'), models.Index(fields=['title'], name='search_sear_title_51a3a1_idx')],
                'unique_together': {('organization', 'object_type', 'object_id')},
            },
        ),
    ]
