# Generated by Django 6.0.4 on 2026-05-12 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_impersonationrequest_ended_at_and_more'),
        ('billing', '0002_invoice_paymentmethod_licensekey_edition_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('checkout', 'Checkout'), ('portal', 'Customer Portal')], max_length=32)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=32)),
                ('provider', models.CharField(default='mock', max_length=80)),
                ('provider_session_id', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(max_length=1000)),
                ('success_url', models.URLField(blank=True)),
                ('cancel_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_portal_sessions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_portal_sessions', to='accounts.organization')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_portal_sessions', to='billing.plan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
