# Generated by Codex on 2026-05-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_impersonationrequest_ended_at_and_more'),
        ('billing', '0003_paymentportalsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='mock', max_length=80)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_notes', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_webhook_events', to='accounts.organization')),
                ('portal_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='billing.paymentportalsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'provider_event_id')},
            },
        ),
    ]
