# Generated by Django 6.0.4 on 2026-05-03 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('queue_name', models.CharField(default='default', max_length=100)),
                ('is_restartable', models.BooleanField(default=True)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('task_name', models.CharField(max_length=255)),
                ('queue_name', models.CharField(default='default', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('retrying', 'Retrying'), ('cancelled', 'Cancelled'), ('revoked', 'Revoked')], default='queued', max_length=32)),
                ('related_object_type', models.CharField(blank=True, max_length=100)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('idempotency_key', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_type', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='tasks.taskdefinition')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_runs', to='accounts.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='tasks.taskrun')),
                ('restarted_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restarts', to='tasks.taskrun')),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRunEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tasks.taskrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
