# Generated by Django 6.0.4 on 2026-05-03 16:06

import django.db.models.deletion
import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('envelopes', '0002_templateparty_formfield_document_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=96, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('opened', 'Opened'), ('submitted', 'Submitted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='created', max_length=32)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='envelopes.envelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signing_sessions', to='envelopes.recipient')),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('typed', 'Typed'), ('drawn', 'Drawn'), ('uploaded', 'Uploaded')], max_length=32)),
                ('typed_name', models.CharField(blank=True, max_length=255)),
                ('image', models.FileField(blank=True, upload_to='signatures/')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='envelopes.envelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='envelopes.recipient')),
                ('signing_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to='signing.signingsession')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_text', models.TextField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='envelopes.envelope')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='envelopes.recipient')),
                ('signing_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to='signing.signingsession')),
            ],
        ),
        migrations.CreateModel(
            name='EnvelopeFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_key', models.SlugField()),
                ('value', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='envelopes.envelope')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='envelopes.formfield')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field_values', to='envelopes.recipient')),
            ],
            options={
                'unique_together': {('envelope', 'field_key', 'recipient')},
            },
        ),
    ]
