# Generated by Django 6.0.4 on 2026-05-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelopefieldvalue',
            name='attachment',
            field=models.FileField(blank=True, upload_to='field_attachments/'),
        ),
    ]
