# Generated by Codex on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signing', '0002_envelopefieldvalue_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signingsession',
            name='status',
            field=models.CharField(
                choices=[
                    ('created', 'Created'),
                    ('opened', 'Opened'),
                    ('submitted', 'Submitted'),
                    ('expired', 'Expired'),
                    ('revoked', 'Revoked'),
                    ('declined', 'Declined'),
                ],
                default='created',
                max_length=32,
            ),
        ),
    ]
