# Generated by Django 6.0.4 on 2026-05-12 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_impersonationrequest'),
        ('configcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.EmailField(default='no-reply@hanmak.local', max_length=254)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('bounce_provider', models.CharField(blank=True, max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_settings', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_timezone', models.CharField(default='UTC', max_length=64)),
                ('default_locale', models.CharField(default='en-US', max_length=32)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='general_settings', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require_mfa', models.BooleanField(default=False)),
                ('allow_passkeys', models.BooleanField(default=True)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=480)),
                ('password_min_length', models.PositiveIntegerField(default=8)),
                ('allowed_ip_ranges', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_settings', to='accounts.organization')),
            ],
        ),
        migrations.CreateModel(
            name='StorageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(default='local', max_length=80)),
                ('bucket_name', models.CharField(blank=True, max_length=255)),
                ('endpoint_url', models.URLField(blank=True)),
                ('retention_days', models.PositiveIntegerField(default=2555)),
                ('encrypt_at_rest', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage_settings', to='accounts.organization')),
            ],
        ),
    ]
