# Generated by Django 6.0.4 on 2026-05-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configcenter', '0004_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='allow_bulk_send',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='allow_mobile_signing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='default_envelope_expiration_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='default_reminder_schedule',
            field=models.CharField(choices=[('none', 'None'), ('daily', 'Daily'), ('every_2_days', 'Every 2 days'), ('every_3_days', 'Every 3 days')], default='every_2_days', max_length=32),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='default_signing_order',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('parallel', 'Parallel')], default='sequential', max_length=32),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='enable_completion_certificates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='require_email_verification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='send_audit_trail_on_completion',
            field=models.BooleanField(default=True),
        ),
    ]
