# Generated by Django 6.0.4 on 2026-05-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configcenter', '0005_generalsettings_allow_bulk_send_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='module',
            field=models.CharField(choices=[('core', 'Core'), ('signing', 'Signing'), ('templates', 'Templates'), ('workflow', 'Workflow'), ('developer', 'Developer'), ('admin', 'Admin'), ('compliance', 'Compliance'), ('billing', 'Billing'), ('integrations', 'Integrations'), ('operations', 'Operations')], default='core', max_length=32),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='owner',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='qa_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='release_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='release_stage',
            field=models.CharField(choices=[('planned', 'Planned'), ('internal', 'Internal QA'), ('beta', 'Beta'), ('released', 'Released'), ('paused', 'Paused'), ('retired', 'Retired')], default='planned', max_length=32),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='rollout_percentage',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='featureflag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
