# Generated by Django 6.0.4 on 2026-05-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_storedfile_document_source_file_documentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True),
        ),
    ]
