# Generated by Django 6.0.4 on 2026-05-03 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_page_count_document_processed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner', models.CharField(default='hanmak-basic', max_length=120)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('clean', 'Clean'), ('infected', 'Infected'), ('failed', 'Failed')], default='queued', max_length=32)),
                ('signature_version', models.CharField(blank=True, max_length=120)),
                ('findings', models.JSONField(blank=True, default=list)),
                ('scanned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
