# Generated by Django 6.0.4 on 2026-05-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencebundle',
            name='signed_pdf',
            field=models.FileField(blank=True, upload_to='signed-pdfs/'),
        ),
        migrations.AddField(
            model_name='evidencebundle',
            name='signed_pdf_sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
