# Generated by Django 6.0.4 on 2026-05-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='html_body',
            field=models.TextField(blank=True),
        ),
    ]
