# Generated by Django 6.0.4 on 2026-05-04 15:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accountrecoveryrequest_passkeychallenge_recoverycode_and_more'),
        ('envelopes', '0003_recipient_delegated_at_recipient_delegated_from_and_more'),
        ('messaging', '0002_emailmessage_html_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='bounce_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='max_attempts',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReminderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_days', models.PositiveIntegerField(default=2)),
                ('max_reminders', models.PositiveIntegerField(default=3)),
                ('reminders_sent', models.PositiveIntegerField(default=0)),
                ('next_run_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='envelopes.envelope')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_schedules', to='accounts.organization')),
            ],
            options={
                'ordering': ['next_run_at'],
            },
        ),
    ]
