# Generated by Django 6.0.4 on 2026-05-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_login_lockout'),
        ('messaging', '0003_emailmessage_bounce_reason_emailmessage_bounced_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('invitation', 'Invitation'), ('envelope_invite', 'Envelope Invite'), ('reminder', 'Reminder'), ('completed', 'Completed')], max_length=32)),
                ('name', models.CharField(max_length=120)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('html_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to='accounts.organization')),
            ],
            options={
                'ordering': ['kind', 'name'],
                'unique_together': {('organization', 'kind', 'name')},
            },
        ),
    ]
